spring:
  application:
    name: eureka-server
    
server:
  port: 4000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka/
    register-with-eureka: false
    fetch-registry: false
