spring:
  application:
    name: stock-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:pocdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
server:
  port: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka/
    register-with-eureka: true
    fetch-registry: true
    
#Application Specific Properties
stock-service:
  request:
    exchange: stock-request-exchange
    queue: stock-request-queue
    routing:
      key: stock-request-routing-key
  reply:
    exchange: stock-reply-exchange
    queue: stock-reply-queue
    routing:
      key: stock-reply-routing-key
