server:
  port: 1000

spring:
  application:
    name: turbine-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka/
    register-with-eureka: true
    fetch-registry: true

turbine:
  appConfig: payment-service
  aggregator:
    clusterConfig: payment-service
#or
#turbine.clusterNameExpression= new String("default")