spring:
  application:
    name: payment-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:pocdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka/
    register-with-eureka: true
    fetch-registry: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
#Application Specific Properties
payment-service:
  request:
    exchange: payment-request-exchange
    queue: payment-request-queue
    routing:
      key: payment-request-routing-key
  reply:
    exchange: payment-reply-exchange
    queue: payment-reply-queue
    routing:
      key: payment-reply-routing-key